# Generated by Django 4.0.5 on 2022-06-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_remove_production_product_hs_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionmany',
            name='product',
        ),
        migrations.AddField(
            model_name='productionmany',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='research.plants', verbose_name='Plants+'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productionmany',
            name='type_product',
        ),
        migrations.AddField(
            model_name='productionmany',
            name='type_product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Product types+', to='research.producttypes'),
            preserve_default=False,
        ),
    ]
